swagger: "2.0"
info:
  version: 1.1.0
  title: IO Function API
  contact:
    name: IO team
    url: https://forum.italia.it/c/progetto-io
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg
  description: >
    Documentation of the IO Function API here.
host: api.cd.italia.it
basePath: "/template"
schemes:
  - https
paths:
  "/echo/{input}":
    parameters:
      - name: input
        in: path
        type: string
        required: true
        description: test input.
    get:
      operationId: echo
      summary: Echo API
      description: Some API description here.
      responses:
        "200":
          description: Found.
          schema:
            "$ref": "#/definitions/Input"
          examples:
            application/json:
              id: "10000AAAA"
              output: "hello world !"
        "401":
          description: Unauthorized
        "404":
          description: Not found.
      parameters: []
definitions:
  Input:
    type: object
    properties:
      id:
        type: string
      output:
        type: string
