name: (CI) Dispatcher

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"
      - ".github/workflows/dispatcher_**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: PR Prod WestEurope
    secrets: inherit
    with:
      environment: prod
      region: westeurope
      base_path: infra/resources
