name: (CD) Dispatcher

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/function_app_dispatcher/**"

jobs:
  release_prod:
    uses: ./.github/workflows/call_release.yaml
    name: Terraform Apply
    secrets: inherit
    with:
      environment: prod
      dir: "infra/function_app_dispatcher"
