name: (CI) Dispatcher

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/function_app_dispatcher/**"
      - ".github/workflows/dispatcher_**"

jobs:
  code_review_prod:
    uses: ./.github/workflows/call_code_review.yaml
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      dir: "infra/function_app_dispatcher"
